stages:
  - test

Pytest:
  image: python:3.9
  stage: test
  services:
    - postgres:13.3
    - redis:6.2.4
  variables:
    # https://docs.gitlab.com/ee/ci/services/postgres.html#use-postgresql-with-the-docker-executor
    POSTGRES_DB: postgres
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: ""
    POSTGRES_HOST_AUTH_METHOD: "trust"
    POSTGRES_SERVICE_HOST: "postgres"
    REDIS_SERVICE_HOST: "redis"
    SECRET_KEY: "secret"
    DEBUG: "1"
  before_script:
    - cd backend
    - pip install -r requirements_dev.txt
  script:
    - flake8
    - black -l 79 -S --check .
    - pytest --cov
  after_script:
    - echo "Pytest tests complete"
  coverage: "/TOTAL.+ ([0-9]{1,3}%)/"
