#  Template python-build

#  This template allows you to validate your python code.
#  The workflow allows running tests and code linting on the default branch.

image: python:3.8

pipelines:
  default:
    - step:
        name: lint and test python code
        caches:
          - pip
        script:
          - pip install -r backend/requirements_dev.txt
          - flake8 backend
          - black -l 79 backend
          - pytest backend
        services:
          - postgres

definitions:
  services:
    postgres:
      image: postgres
      variables:
        POSTGRES_DB: 'postgres'
        POSTGRES_USER: 'postgres'
        POSTGRES_PASSWORD: 'postgres'