services:

  # used only to get the certificate from certbot - this keeps things clean
  nginx-init:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/ec2/init.conf:/etc/nginx/conf.d/default.conf:ro
      - ./web-content:/usr/share/nginx/html:ro
      - certbot-etc:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    command: ["nginx", "-g", "daemon off;"]

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/ec2/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./web-content:/usr/share/nginx/html:ro
      - certbot-etc:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    command: ["nginx", "-g", "daemon off;"]

  # Certbot: Run this one time to get the certificate
  certbot-init:
    image: certbot/certbot
    container_name: certbot-init
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email briancaffey2010@gmail.com --agree-tos --no-eff-email -d ec2.briancaffey.com

  # Automatically renew SSL and reload NGINX
  certbot-renew:
    image: certbot/certbot
    container_name: certbot-renew
    restart: always
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    entrypoint: /bin/sh -c "
      trap exit TERM;
      while :;
      do
        certbot renew --webroot -w /var/www/certbot;
        if [ -f /etc/letsencrypt/live/ec2.briancaffey.com/fullchain.pem ]; then
          echo 'SSL Certificate exists. Reloading NGINX...';
          docker exec nginx nginx -s reload;
        fi;
        sleep 12h;
      done"

volumes:
  certbot-etc:
  certbot-www:
