FROM python:3.9
ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1
RUN mkdir /code
WORKDIR /code
ADD requirements_dev.txt /code/
RUN pip3 install -r requirements_dev.txt
ADD . /code/
RUN useradd -m app
USER app