FROM python:3.8
ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1
RUN mkdir /code
WORKDIR /code

# Install poetry for development
ENV POETRY_VERSION=1.0.0
RUN pip install "poetry==$POETRY_VERSION"

ADD requirements_dev.txt /code/
RUN pip3 install -r requirements_dev.txt
ADD . /code/
RUN useradd -m app
USER app