# Generated by Django 3.1.13 on 2021-07-04 03:32

import backend.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                storage=backend.storage_backends.PrivateMediaStorage(),
                upload_to="images",
            ),
        ),
    ]
