# Generated by Django 3.1.5 on 2021-03-25 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-modified_on',)},
        ),
    ]
