# Generated by Django 3.1.5 on 2021-03-26 02:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210326_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlike',
            name='like_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
