# Generated by Django 3.1.5 on 2021-03-26 02:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_postlike_like_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postlike',
            old_name='like_on',
            new_name='liked_on',
        ),
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together={('liked_by', 'post')},
        ),
    ]
