# github action to create or update an ad hoc environment
name: ad hoc | app | create / update

on:
  workflow_dispatch:
    inputs:

      # The Terraform workspace for the shared resources Terraform configuration
      # that the ad hoc environment will use.
      # This input typically will not be used since all ad hoc environments should use one set of shared resources
      # This may be changed if major changes to the shared resources configuration are made to avoid disrupting existing ad hoc environments
      shared_resources_workspace:
        description: 'Terraform workspace for shared resources env'
        required: true
        default: 'dev'
        type: string

      workspace:
        description: 'Terraform workspace for the ad hoc env'
        required: true
        default: 'dev'
        type: string

jobs:
  create_update_ad_hoc_env:
    name: "Create or update ad hoc env [${{ github.event.inputs.workspace }}]"
    environment: ad-hoc-env-${{ github.event.inputs.workspace }}
    runs-on: ubuntu-latest

    steps:
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.6
          terraform_wrapper: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - uses: actions/checkout@v3

      # get the values for the Terraform configuration for the shared resources: BASTION_IP, RDS_ENDPOINT, etc.
      - name: "Get AWS Resource values"
        id: get_aws_resource_values
        env:
          SHARED_RESOURCES_ENV: ${{ github.event.inputs.shared_resources_workspace }}
        run: |
          BASTION_INSTANCE_ID=$(aws ec2 describe-instances \
            --filters "Name=tag:env,Values=$SHARED_RESOURCES_ENV" \
            --filters "Name=instance-state-name,Values=running" \
            --query "Reservations[*].Instances[*].InstanceId" \
            --output text)

          RDS_ENDPOINT=$(aws rds describe-db-instances \
            --db-instance-identifier $SHARED_RESOURCES_ENV-rds \
            --query "DBInstances[0].Endpoint.Address" \
            --output text)

          echo "rds_endpoint=$RDS_ENDPOINT" >> $GITHUB_ENV
          echo "bastion_instance_id=$BASTION_INSTANCE_ID" >> $GITHUB_ENV

      - name: "Create ad hoc environment DB"
        id: create_ad_hoc_env_db
        env:
          RDS_ENDPOINT: ${{ env.rds_endpoint }}
          BASTION_INSTANCE_ID: ${{ env.bastion_instance_id }}
          AD_HOC_ENV: ${{ github.event.inputs.workspace }}
          AWS_PAGER: ""
        run: |
          # TODO - move the hard-coded password to secrets manager and retrieve it from AWS Secrets Manager
          # define the command to create the database
          export COMMAND="PGPASSWORD=postgres createdb -U postgres -w -h $RDS_ENDPOINT $AD_HOC_ENV-db || echo DB either already exists or could not be created"

          # send the command and capture the output to get the command ID
          SEND_COMMAND_OUTPUT=$( \
            aws ssm send-command \
              --instance-ids "${BASTION_INSTANCE_ID}" \
              --document-name "AWS-RunShellScript" \
              --parameters '{"commands": ["'"${COMMAND}"'"]}' \
          )

          # get the command ID
          COMMAND_ID=$(echo $SEND_COMMAND_OUTPUT | jq -r '.Command.CommandId')

          # wait for the command to complete
          aws ssm wait command-executed \
            --command-id $COMMAND_ID \
            --instance-id ${BASTION_INSTANCE_ID}

          echo "Command Completed.."

          # get command output for StdOut and StdErr content
          COMMAND_INFO=$( \
            aws ssm get-command-invocation \
              --command-id $COMMAND_ID \
              --instance-id "${BASTION_INSTANCE_ID}" \
          )

          echo $COMMAND_INFO

          # get the command output
          echo $COMMAND_INFO | jq -r '.StandardOutputContent'
          echo $COMMAND_INFO | jq -r '.StandardErrorContent'

      - name: "terraform init, plan and apply for ad hoc environment"
        id: terraform_init_plan_apply
        env:
          # Terraform workspace (from the workflow input)
          WORKSPACE: ${{ github.event.inputs.workspace }}

          # backend config variables
          TF_BACKEND_BUCKET: ${{ secrets.TF_BACKEND_BUCKET }}
          TF_BACKEND_REGION: ${{ secrets.TF_BACKEND_REGION }}
          TF_BACKEND_DYNAMODB_TABLE: ${{ secrets.TF_BACKEND_DYNAMODB_TABLE }}

          # Terraform variables (TF_VAR_)
          # variables for accessing shared resources over terraform_remote_state
          TF_VAR_shared_resources_workspace: ${{ github.event.inputs.shared_resources_workspace }}
          TF_VAR_s3_bucket: ${{ secrets.TF_BACKEND_BUCKET }}

          # ECR variables
          TF_VAR_ecr_be_repo_url: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/backend
          TF_VAR_ecr_fe_repo_url: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/frontend

          # Route 53 variables
          TF_VAR_domain_name: ${{ secrets.DOMAIN_NAME }}

        run: |

          # set the relative path of the .tfvars file corresponding to the workspace
          export VAR_FILE=envs/${WORKSPACE}.tfvars

          # init
          terraform -chdir=iac/terraform/live/ad-hoc/app \
            init \
            -input=false \
            -backend-config="bucket=${TF_BACKEND_BUCKET}" \
            -backend-config="dynamodb_table=${TF_BACKEND_DYNAMODB_TABLE}" \
            -backend-config="key=terraform.tfstate" \
            -backend-config="region=${TF_BACKEND_REGION}" \
            -backend-config="workspace_key_prefix=ad-hoc-envs"

          # create the workspace if it doesn't exist already
          terraform workspace new ${WORKSPACE} || echo "Workspace ${WORKSPACE} already exists or cannot be created"

          # set the TF_WORKSPACE environment variable
          export TF_WORKSPACE=$WORKSPACE

          # plan
          terraform -chdir=iac/terraform/live/ad-hoc/app \
            plan \
            -no-color \
            -var-file=$VAR_FILE

          # apply
          terraform -chdir=iac/terraform/live/ad-hoc/app \
            apply \
            -auto-approve \
            -var-file=$VAR_FILE

          # output
          terraform -chdir=iac/terraform/live/ad-hoc/app \
            output \
            -json > terraform_outputs.json

      # Migration and collectstatic commands
      - name: "Run post-deployment steps"
        id: post_ad_hoc_env_create_update
        env:
          AD_HOC_ENV: ${{ github.event.inputs.workspace }}
        run: |

          # get the migrate command from Terraform outputs and write to file
          cat terraform_outputs.json | jq -r '.backend_update_command.value' > backend_update_command.sh

          # view migrate command
          cat backend_update_command.sh

          # make the file executable
          sudo chmod +x backend_update_command.sh

          # run migrate command
          ./backend_update_command.sh
