# github action to destroy shared resources
name: ad hoc | base | destroy

on:
  workflow_dispatch:
    inputs:
      workspace:
        description: 'Terraform workspace for ad hoc base env'
        required: true
        default: 'dev'
        type: string

jobs:
  destroy_ad_hoc_base_env:
    name: "Destroy shared resources env [${{ github.event.inputs.workspace }}]"
    environment: ad-hoc-base-${{ github.event.inputs.workspace }}
    runs-on: ubuntu-latest

    steps:

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.7
          terraform_wrapper: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "terraform destroy for shared resources"
        id: terraform_init_plan_apply_ad_hoc_base
        env:
          TF_BACKEND_BUCKET: ${{ secrets.TF_BACKEND_BUCKET }}
          TF_BACKEND_KEY: ${{ secrets.TF_BACKEND_KEY }}
          TF_BACKEND_REGION: ${{ secrets.TF_BACKEND_REGION }}
          TF_BACKEND_DYNAMODB_TABLE: ${{ secrets.TF_BACKEND_DYNAMODB_TABLE }}
          WORKSPACE: ${{ github.event.inputs.workspace }}

          # Terraform variables
          TF_VAR_certificate_arn: ${{ secrets.ACM_CERTIFICATE_ARN }}
          TF_VAR_key_name: ${{ secrets.KEY_NAME }}

        run: |
          export VAR_FILE=envs/${WORKSPACE}.tfvars

          terraform -chdir=terraform/live/ad-hoc/base \
            init \
            -backend-config="bucket=${TF_BACKEND_BUCKET}" \
            -backend-config="dynamodb_table=${TF_BACKEND_DYNAMODB_TABLE}" \
            -backend-config="key=terraform.tfstate" \
            -backend-config="region=${TF_BACKEND_REGION}" \
            -backend-config="workspace_key_prefix=shared-resources"

          # create the workspace if it doesn't exist already
          terraform workspace new ${WORKSPACE} || echo "Workspace ${WORKSPACE} already exists or cannot be created"

          # set the TF_WORKSPACE environment variable
          export TF_WORKSPACE=$WORKSPACE

          terraform -chdir=terraform/live/ad-hoc/base destroy -auto-approve
