# github action to create or update shared resources
name: ad hoc | base | create / update [CDK]

on:
  workflow_dispatch:
    inputs:
      ad_hoc_base_name:
        description: 'Name for ad hoc base environment to create/update using CDK'
        required: true
        default: 'dev'
        type: string

jobs:
  ad_hoc_base_synth:
    name: "Create or update ad hoc base infrastructure using CDK [${{ github.event.inputs.ad_hoc_base_name }}]"
    environment: ad-hoc-base-${{ github.event.inputs.ad_hoc_base_name }}
    env:
      AD_HOC_BASE_NAME: ${{ github.event.inputs.ad_hoc_base_name }}
      ACM_CERTIFICATE_ARN: ${{ secrets.ACM_CERTIFICATE_ARN }}
      DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
    runs-on: ubuntu-latest

    steps:

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install CDK
        run: |
          cd iac/cdk/ && npm install && npm i -g aws-cdk

      - name: Build
        run: |
          cd iac/cdk/ && tsc

      - name: "cdk diff"
        id: cdk_diff
        run: |
          cd iac/cdk/ && cdk diff --app='lib/ad-hoc/index.js' -e ExampleAdHocBaseStack --require-approval never

      - name: "cdk synth"
        id: cdk_synth
        run: |
          cd iac/cdk/ && cdk synth --app='lib/ad-hoc/index.js' -e ExampleAdHocBaseStack --require-approval never

      - name: Save synth output to artifact
        uses: actions/upload-artifact@v2
        with:
          name: synth-output
          path: iac/cdk/cdk.out

  ad_hoc_base_deploy:
    name: "Ad hoc base deploy"
    environment: ad-hoc-base
    runs-on: ubuntu-latest
    needs: ad_hoc_base_synth

    steps:

      - uses: actions/download-artifact@v2
        with:
          name: synth-output

      - name: "cdk deploy"
        id: cdk_deploy
        run: |
          cd iac/cdk/ && cdk deploy --app cdk.out -e ExampleAdHocBaseStack --require-approval never
