# github action to destroy an ad hoc environment
name: Ad Hoc Env / DESTROY

on:
  workflow_dispatch:
    inputs:

      shared_resources_workspace:
        description: 'Terraform workspace for shared resources env'
        required: true
        default: 'dev'
        type: string

      workspace:
        description: 'Terraform workspace for ad hoc env to destroy'
        required: true
        default: 'dev'
        type: string

jobs:
  destroy_ad_hoc_env:
    name: "Destroy ad hoc env [${{ github.event.inputs.workspace }}]"
    environment: ad-hoc-env-${{ github.event.inputs.workspace }}
    runs-on: ubuntu-latest

    steps:

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.7

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "terraform destroy"
        id: terraform_destroy
        env:
          # Terraform workspace (from the workflow input)
          WORKSPACE: ${{ github.event.inputs.workspace }}

          # backend config variables
          TF_BACKEND_BUCKET: ${{ secrets.TF_BACKEND_BUCKET }}
          TF_BACKEND_REGION: ${{ secrets.TF_BACKEND_REGION }}

          # Terraform variables (TF_VAR_)
          # variables for accessing shared resources over terraform_remote_state
          TF_VAR_shared_resources_workspace: ${{ github.event.inputs.shared_resources_workspace }}
          TF_VAR_s3_bucket: ${{ secrets.TF_BACKEND_BUCKET }}

          # ECR variables
          TF_VAR_ecr_be_repo_url: ${{ secrets.BACKEND_IMAGE_URI }}
          TF_VAR_ecr_fe_repo_url: ${{ secrets.FRONTEND_IMAGE_URI }}

          # ACM variables
          TF_VAR_acm_certificate_arn: ${{ secrets.ACM_CERTIFICATE_ARN }}

          # Route 53 variables
          TF_VAR_domain_name: ${{ secrets.DOMAIN_NAME }}

        run: |
          # set the terraform workspace
          # export TF_WORKSPACE=$WORKSPACE
          # terraform workspace select $WORKSPACE || terraform workspace new $WORKSPACE

          terraform -chdir=terraform/live/ad-hoc \
            init \
            -input=false \
            -backend-config="bucket=${TF_BACKEND_BUCKET}" \
            -backend-config="key=terraform.tfstate" \
            -backend-config="region=${TF_BACKEND_REGION}" \
            -backend-config="workspace_key_prefix=ad-hoc-envs"

          # set the terraform workspace
          terraform workspace new $WORKSPACE

          if [ $? == 1] then
            # if the workspace cannot be created, then it already exists, select it
            terraform workspace select $WORKSPACE
          fi

          terraform workspace list

          sleep 50


          terraform -chdir=terraform/live/ad-hoc destroy -auto-approve
