name: '[CDK] CDK GitHub Action'
run-name: '[CDK] Actions'

on:
  workflow_dispatch:
    inputs:
      STACK:
        required: true
        description: "Name of stack that will be deployed or destroyed"
      DIRECTORY:
        required: true
        description: "Relative path the directory where CDK command will run"

jobs:
  cdk:
    name: "CDK"
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest

    steps:

      # Switch to role auth
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - uses: actions/checkout@v4

      - name: Setup Node LTS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn
          cache-dependency-path: './iac/cdk/yarn.lock'

      - name: Installing dependencies 📦️
        working-directory: 'iac/cdk'
        run: yarn install

      - name: install CDK
        run: |
          npm install -g aws-cdk

      - name: Build
        working-directory: 'iac/cdk'
        env:
          ACM_CERTIFICATE_ARN: ${{ secrets.ACM_CERTIFICATE_ARN }}
          DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
        run: |
          tsc

      - name: CDK Action
        working-directory: 'iac/cdk'
        env:
          ACM_CERTIFICATE_ARN: ${{ secrets.ACM_CERTIFICATE_ARN }}
          DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
        run: |
          ls lib || echo 'error buidling'
          cdk deploy --app='./lib/ad-hoc/index.js' -e ${{ inputs.STACK }}
