# a github action that builds and deploys the project using docker commands and ssh
name: build, test, push images and docker stack deploy to docker swarm

on:
  push:
    tags:
      - 'cdk/v*'

jobs:
  deploy:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
    name: "Deploy to docker swarm"
    environment: docker-swarm-ec2
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Git version info"
        id: git_version_info
        run: |
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      # check to see if the CloudFormation stack called $STACK_NAME exists
      # if it does not exist, run the steps for cdk deploy
      - name: Check existence of CloudFormation stack
        id: cfn_stack_check
        env:
          GIT_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          # TODO - check to see if the stack exists with aws cloudformation describe-stacks call
          RUN_CDK_DEPLOY=false
          if [[ "$GIT_COMMIT_MESSAGE" == *[cdk]* ]]; then RUN_CDK_DEPLOY=true; fi
          echo ::set-output name=RUN_CDK_DEPLOY::$RUN_CDK_DEPLOY

      - name: Use Node.js
        if: steps.cfn_stack_check.outputs.RUN_CDK_DEPLOY == 'true'
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install CDK
        if: steps.cfn_stack_check.outputs.RUN_CDK_DEPLOY == 'true'
        run: |
          npm install -g aws-cdk@1.134.0

      - name: Deploy CDK Stack
        if: steps.cfn_stack_check.outputs.RUN_CDK_DEPLOY == 'true'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
          KEY_PAIR_NAME: ${{ secrets.KEY_PAIR_NAME }}
          STACK_NAME: ${{ secrets.STACK_NAME }}
        run: |
          # make cdk-diff-docker-ec2
          make cdk-deploy-docker-ec2

      - name: "Get CloudFormation Stack Outputs"
        if: steps.cfn_stack_check.outputs.RUN_CDK_DEPLOY == 'false'
        id: stack_outputs
        env:
          STACK_NAME: ${{ secrets.STACK_NAME }}
        run: |
          aws cloudformation describe-stacks \
            --stack-name $STACK_NAME \
            --query 'Stacks[0].Outputs' \
            --output json > /tmp/stack_outputs.json

          SWARM_LEADER_PUBLIC_IP=$(cat /tmp/stack_outputs.json | jq -r '.[] | select(.ExportName == "Ec2PublicIpAddress") | .OutputValue')
          KEY_PAIR_NAME=$(cat /tmp/stack_outputs.json | jq -r '.[] | select(.ExportName == "Ec2KeyName") | .OutputValue')
          PORTAINER_HOST_NAME=$(cat /tmp/stack_outputs.json | jq -r '.[] | select(.ExportName == "PortainerHostName") | .OutputValue')
          APPLICATION_HOST_NAME=$(cat /tmp/stack_outputs.json | jq -r '.[] | select(.ExportName == "ApplicationHostName") | .OutputValue')
          FRONTEND_REPOSITORY_URI=$(cat /tmp/stack_outputs.json | jq -r '.[] | select(.ExportName == "FrontendRepositoryUri") | .OutputValue')
          BACKEND_REPOSITORY_URI=$(cat /tmp/stack_outputs.json | jq -r '.[] | select(.ExportName == "BackendRepositoryUri") | .OutputValue')
          S3_BUCKET_NAME=$(cat /tmp/stack_outputs.json | jq -r '.[] | select(.ExportName == "S3BucketName") | .OutputValue')

          echo ::set-output name=SWARM_LEADER_PUBLIC_IP::$SWARM_LEADER_PUBLIC_IP
          echo ::set-output name=KEY_PAIR_NAME::$KEY_PAIR_NAME
          echo ::set-output name=PORTAINER_HOST_NAME::$PORTAINER_HOST_NAME
          echo ::set-output name=APPLICATION_HOST_NAME::$APPLICATION_HOST_NAME
          echo ::set-output name=FRONTEND_REPOSITORY_URI::$FRONTEND_REPOSITORY_URI
          echo ::set-output name=BACKEND_REPOSITORY_URI::$BACKEND_REPOSITORY_URI
          echo ::set-output name=S3_BUCKET_NAME::$S3_BUCKET_NAME

      # ⚠️ this did not work when trying to establish an ssh connection to the ec2 host ⚠️
      # - name: "Install SSH Key"
      #   uses: shimataro/ssh-key-action@v2
      #   with:
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     name: id_rsa
      #     known_hosts: ${{ steps.get_instance_data.outputs.SWARM_LEADER_PUBLIC_IP }}

      - name: "Setup SSH Key"
        if: steps.cfn_stack_check.outputs.RUN_CDK_DEPLOY == 'false'
        id: setup_ssh_key
        env:
          SWARM_HOST_IP: ${{ steps.stack_outputs.outputs.SWARM_LEADER_PUBLIC_IP }}
        run: |
          # setup key pair for SSH access
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan -H $SWARM_HOST_IP >> ~/.ssh/known_hosts

      - name: "Build Backend Docker Container"
        if: steps.cfn_stack_check.outputs.RUN_CDK_DEPLOY == 'false'
        env:
          SOURCE_TAG: ${{ steps.git_version_info.outputs.SOURCE_TAG }}
          BACKEND_IMAGE_URI: ${{ steps.stack_outputs.outputs.BACKEND_REPOSITORY_URI }}
          FRONTEND_IMAGE_URI: ${{ steps.stack_outputs.outputs.FRONTEND_REPOSITORY_URI }}
          APPLICATION_HOST_NAME: ${{ steps.stack_outputs.outputs.APPLICATION_HOST_NAME }}

        run: |
          ## get ECR repository URI

          # login to ECR backend image repository
          aws ecr get-login-password \
            --region us-east-1 \
            | docker login \
            --username AWS \
            --password-stdin $BACKEND_IMAGE_URI

          docker build \
            --build-arg SOURCE_TAG=$SOURCE_TAG \
            -t $BACKEND_IMAGE_URI \
            ./backend

          docker tag $BACKEND_IMAGE_URI $BACKEND_IMAGE_URI:$SOURCE_TAG

          docker push $BACKEND_IMAGE_URI:$SOURCE_TAG

      - name: "Build and Push Frontend Docker Container"
        if: steps.cfn_stack_check.outputs.RUN_CDK_DEPLOY == 'false'
        env:
          SOURCE_TAG: ${{ steps.git_version_info.outputs.SOURCE_TAG }}
          FRONTEND_IMAGE_URI: ${{ steps.stack_outputs.outputs.FRONTEND_REPOSITORY_URI }}
          APPLICATION_HOST_NAME: ${{ steps.stack_outputs.outputs.APPLICATION_HOST_NAME }}

        run: |
          ## get ECR repository URI

          # login to ECR backend image repository
          aws ecr get-login-password \
            --region us-east-1 \
            | docker login \
            --username AWS \
            --password-stdin $FRONTEND_IMAGE_URI

          docker build \
              --build-arg BACKEND_API_URL=https://$APPLICATION_HOST_NAME \
              -t $FRONTEND_IMAGE_URI \
              -f nginx/prod/Dockerfile \
              .

          docker tag $FRONTEND_IMAGE_URI $FRONTEND_IMAGE_URI:$SOURCE_TAG
          docker push $FRONTEND_IMAGE_URI:$SOURCE_TAG

      - name: "docker stack deploy"
        if: steps.cfn_stack_check.outputs.RUN_CDK_DEPLOY == 'false'
        env:
          SWARM_HOST_IP: ${{ steps.stack_outputs.outputs.SWARM_LEADER_PUBLIC_IP }}
          SOURCE_TAG: ${{ steps.git_version_info.outputs.SOURCE_TAG }}
          BACKEND_IMAGE_URI: ${{ steps.stack_outputs.outputs.BACKEND_REPOSITORY_URI }}
          FRONTEND_IMAGE_URI: ${{ steps.stack_outputs.outputs.FRONTEND_REPOSITORY_URI }}
          APPLICATION_HOST_NAME: ${{ steps.stack_outputs.outputs.APPLICATION_HOST_NAME }}
          PORTAINER_HOST_NAME: ${{ steps.stack_outputs.outputs.PORTAINER_HOST_NAME }}
          S3_BUCKET_NAME: ${{ steps.stack_outputs.outputs.S3_BUCKET_NAME }}
        run: |
          export DOCKER_HOST=ssh://ec2-user@$SWARM_HOST_IP

          # login to ECR backend image repository
          aws ecr get-login-password \
            --region us-east-1 \
            | docker login \
            --username AWS \
            --password-stdin $FRONTEND_IMAGE_URI

          # login to ECR backend image repository
          aws ecr get-login-password \
            --region us-east-1 \
            | docker login \
            --username AWS \
            --password-stdin $BACKEND_IMAGE_URI

          # this is probably not needed
          export BACKEND_IMAGE_URI=$BACKEND_IMAGE_URI:$SOURCE_TAG
          export FRONTEND_IMAGE_URI=$FRONTEND_IMAGE_URI:$SOURCE_TAG
          export APPLICATION_HOST_NAME=$APPLICATION_HOST_NAME
          export PORTAINER_HOST_NAME=$PORTAINER_HOST_NAME
          export S3_BUCKET_NAME=$S3_BUCKET_NAME

          # TODO: add --prune option to remove unused images
          docker stack deploy --with-registry-auth -c stack.yml stack
